### ISSUE TITLE
Placeholder - enabled or not

### ISSUE THREAD

**Issue by bobhenl** [ExyronProvider/FastCrystalsPlugin#11]
Hello, can you add hook to PAPI showing if the user has enabled or disabled fastcrystals? Like "enabled" "disabled"? Can be useful when we want to add it to the settings menu & show the current state

**Comment by KinczeK** [comment]
Done, new placeholder entry looks like this: %fastcrystals_status% and returns value from configuration if it's enabled or not.

**Comment by bobhenl** [comment]
Thanks a lot!
